global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "demoapi"
    static_configs:
    - targets: ["demoapi:5000"]
